" Vim filetype plugin file
" Language:    HTML
" Maintainer:  Damien Gombault <desintegr@gmail.com>
" Last Change: 2007 Oct 26

" Auto tags
inoremap <buffer> </ </<C-x><C-o><Esc>a
inoremap <buffer> <!D <!D<C-x><C-o>

" Special chars
inoremap <buffer> && &amp;
inoremap <buffer> &cO &copy;
inoremap <buffer> &rO &reg;
inoremap <buffer> &tm &trade;
inoremap <buffer> &' &quot;
inoremap <buffer> &< &lt;
inoremap <buffer> &> &gt;
inoremap <buffer> &<space> &nbsp;
inoremap <buffer> <lead><space> &nbsp;
inoremap <buffer> &# &pound;
inoremap <buffer> &Y= &yen;
inoremap <buffer> &e= &euro;
inoremap <buffer> &c\\| &cent;
inoremap <buffer> &A` &Agrave;
inoremap <buffer> &A' &Aacute;
inoremap <buffer> &A^ &Acirc;
inoremap <buffer> &A~ &Atilde;
inoremap <buffer> &A\" &Auml;
inoremap <buffer> &Ao &Aring;
inoremap <buffer> &AE &AElig;
inoremap <buffer> &C, &Ccedil;
inoremap <buffer> &E` &Egrave;
inoremap <buffer> &E' &Eacute;
inoremap <buffer> &E^ &Ecirc;
inoremap <buffer> &E\" &Euml;
inoremap <buffer> &I` &Igrave;
inoremap <buffer> &I' &Iacute;
inoremap <buffer> &I^ &Icirc;
inoremap <buffer> &I\" &Iuml;
inoremap <buffer> &N~ &Ntilde;
inoremap <buffer> &O` &Ograve;
inoremap <buffer> &O' &Oacute;
inoremap <buffer> &O^ &Ocirc;
inoremap <buffer> &O~ &Otilde;
inoremap <buffer> &O\" &Ouml;
inoremap <buffer> &O/ &Oslash;
inoremap <buffer> &U` &Ugrave;
inoremap <buffer> &U' &Uacute;
inoremap <buffer> &U^ &Ucirc;
inoremap <buffer> &U\" &Uuml;
inoremap <buffer> &Y' &Yacute;
inoremap <buffer> &a` &agrave;
inoremap <buffer> &a' &aacute;
inoremap <buffer> &a^ &acirc;
inoremap <buffer> &a~ &atilde;
inoremap <buffer> &a\" &auml;
inoremap <buffer> &ao &aring;
inoremap <buffer> &ae &aelig;
inoremap <buffer> &c, &ccedil;
inoremap <buffer> &e` &egrave;
inoremap <buffer> &e' &eacute;
inoremap <buffer> &e^ &ecirc;
inoremap <buffer> &e\" &euml;
inoremap <buffer> &i` &igrave;
inoremap <buffer> &i' &iacute;
inoremap <buffer> &i^ &icirc;
inoremap <buffer> &i\" &iuml;
inoremap <buffer> &n~ &ntilde;
inoremap <buffer> &o` &ograve;
inoremap <buffer> &o' &oacute;
inoremap <buffer> &o^ &ocirc;
inoremap <buffer> &o~ &otilde;
inoremap <buffer> &o\" &ouml;
inoremap <buffer> &x &times;
inoremap <buffer> &u` &ugrave;
inoremap <buffer> &u' &uacute;
inoremap <buffer> &u^ &ucirc;
inoremap <buffer> &u\" &uuml;
inoremap <buffer> &y' &yacute;
inoremap <buffer> &y\" &yuml;
inoremap <buffer> &2< &laquo;
inoremap <buffer> &2> &raquo;
inoremap <buffer> &\" &uml;
inoremap <buffer> &/ &divide;
inoremap <buffer> &o/ &oslash;
inoremap <buffer> &! &iexcl;
inoremap <buffer> &? &iquest;
inoremap <buffer> &de &deg;
inoremap <buffer> &mu &micro;
inoremap <buffer> &pa &para;
inoremap <buffer> &. &middot;
inoremap <buffer> &14 &frac14;
inoremap <buffer> &12 &frac12;
inoremap <buffer> &34 &frac34;
inoremap <buffer> &n- &ndash;
inoremap <buffer> &m- &mdash;
inoremap <buffer> &-- &mdash;
inoremap <buffer> &3. &hellip;
